#!/usr/bin/python3

import os
from PIL import Image

def convert_images():

    files = [file for file in os.listdir() if os.path.isfile(file)]

    errors = ""

    for file in files:
        try:
            with Image.open(file) as img:
                if img.format == 'WEBP':
                    img.save(file + '.jpg')
        except OSError as error:
            errors += str(error) + "\n"

    print("no errors") if len(errors) == 0 else print(errors)
    return 0

convert_images()
